<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Albums\Module'                        => __DIR__ . '/Module.php',
    'Albums\Controller\AlbumsController' => __DIR__ . '/src/Albums/Controller/AlbumsController.php',
    'AlbumsTest\Framework\TestCase'        => __DIR__ . '/tests/Albums/Framework/TestCase.php',
    'AlbumsTest\SampleTest'                => __DIR__ . '/tests/Albums/SampleTest.php',
);
