<?php
if($this->form){
    $this->form->prepare();

    echo $this->form()->openTag($this->form);

    echo $this->formRow($this->form->get('soloFieldset')
        ->get('id'));

    echo $this->formRow($this->form->get('soloFieldset')
        ->get('name'));

    echo $this->formRow($this->form->get('soloFieldset')
        ->get('description'));

    echo $this->formSubmit($this->form->get('submit'));
    echo $this->form()->closeTag();
}
