<?php
$title = 'Meine Plattensammlung';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('albums', 
    		array(
				'action' => 'add-album')
			);?>">Neue Platte hinzufügen</a>
</p>

<table class="table">
<tr>
    <th>Titel</th>
    <th>Künstler</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('albums', 
            array(
				'action' => 'edit-album', 
				'id' => $album->id)
			);?>">Bearbeiten</a> |
        <a href="<?php echo $this->url('albums',
            array(
				'action' => 'delete-album',
				'id' => $album->id)
			);?>">Löschen</a>
    </td>
</tr>
<?php endforeach; ?>
</table>