<div class="header">
    <h1>Roles</h1>
</div>
<div class="content">
    <?php if (count($this->roleObj)): ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Name'); ?></th>
        </tr>
        </thead>
        <tbody><?php foreach ($this->roleObj as $roleObj): ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($roleObj->getId()); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($roleObj->getName()); ?>
            </td>
        </tr>
        <?php endforeach ?>
        </tbody>
    <?php endif ?>
    </table>
</div>


