<?php
if ($this->form) {
    $this->form->prepare();

    echo $this->form()->openTag($this->form);

    echo $this->formRow($this->form->get('crud-collection-user-fieldset')
        ->get('id'));

    echo $this->formRow($this->form->get('crud-collection-user-fieldset')
        ->get('email'));

    echo $this->formRow($this->form->get('crud-collection-user-fieldset')
        ->get('name'));

    echo $this->formCollection($this->form->get('crud-collection-user-fieldset')
        ->get('userAddresses'));

    echo $this->formSubmit($this->form->get('submit'));
    echo $this->form()->closeTag();
}