<div class="header">
    <h1>Create Module</h1>
</div>
<?php
$formName = $this->moduleCreate;
$fieldsetName = $formName->get('moduleCreateFieldset');

//$class = 'form-horizontal';
//echo $this->showForm($moduleCreateForm, $class);

if ($formName) {
    $formName->prepare();

    echo $this->form()->openTag($formName);

    echo $this->formRow($fieldsetName->get('id'));

    echo $this->formRow($fieldsetName->get('name'));
    echo $this->formRow($fieldsetName->get('description'));
    echo $this->formRow($fieldsetName->get('isActive'));

    echo $this->formSubmit($formName->get('submit'));

    echo $this->form()->closeTag();
}



